
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nimbyx.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class GoogleProduct
{

    public int Id { get; set; }

    public int ProductId { get; set; }

    public string Taxonomy { get; set; }

    public bool CustomGoods { get; set; }

    public string Gender { get; set; }

    public string AgeGroup { get; set; }

    public string Color { get; set; }

    public string Size { get; set; }

    public string Material { get; set; }

    public string Pattern { get; set; }

    public string ItemGroupId { get; set; }

}

}
